
language: node_js
node_js:
  - 8
  - 10

env:
  - NODE_ENV=development

before_install:
  - npm i -g coveralls

install:
  - npm install

cache:
  directories:
    - "node_modules"
    - ".rpt2_cache"

script:
  - npm test

after_script:
  - coveralls < ./coverage/lcov.info

notifications:
email: false